version: '3'

services:
  mysql:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=fa109097
      - MYSQL_DATABASE=gestaoemprestimos
      - MYSQL_ROOT_HOST=%
    volumes:
      - /data/mysql
  bra:
    image: faustotna/gestaoemprestimos
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - /data/gestaoemprestimos